language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

  
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  
# command to install dependencies
install:
  - pip install numpy pillow nose pytest

# command to run tests
script: python -m pytest