language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

  
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  
# command to install dependencies
install:
  - pip install numpy pillow nose pytest

# command to run tests
script: python /home/travis/build/Allong12/py-scrcpy/scrcpy_client_tests.py